version: '3.8'
services:
  wordpress_app:
    build: ./wordpress_app
    depends_on:
      - mysql_app
    ports:
      - 80:80
    volumes:
      - ./wordpress_app/app:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mysql_app
      - WORDPRESS_DB_NAME=wordpress_db
      - WORDPRESS_DB_USER=abdullah
      - WORDPRESS_DB_PASSWORD=abdullah123
    networks:
      - my_network
  mysql_app:
    build: ./mysql_app
    ports:
      - 3306:3306
    volumes:
      - ./mysql_app/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abdullah123
      - MYSQL_DATABASE=wordpress_db
      - MYSQL_USER=abdullah
      - MYSQL_PASSWORD=abdullah123
    networks:
      - my_network
networks:
  my_network: 
    driver: bridge
